### ISSUE TITLE
Add support for Singularity.* filetypes.

### ISSUE THREAD

**Issue by mbhall88** [singularityhub/language-singularity#2]
I tend to name my recipes files as `Singularity.foo` so would be good to get the grammar to detect these files. I tried adding `Singularity.` and also `Singularity.*` to the `fileTypes` array but didn't work.  
I will keep trying to see if I can get this working.  
Happy to give this up though if that naming convention is considered bad form?

**Comment by vsoch** [comment]
No not at all! I didn't test that use case and missed it! The extension of the Singularity file corresponds to the tag on Singularity Hub. The fileName field should be at the top of the grammars file. Do you want to tweak, and submit the fix as a PR?

**Comment by vsoch** [comment]
And yes, **don't give it up!**

https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by mbhall88** [comment]
Ok will fix it up when I get home in about an hour.

**Comment by vsoch** [comment]
okay cool! This is really fun :o_) open source, random twitter collaboration ftw!! :tada:

**Comment by mbhall88** [comment]
Hmmm the `fileName` field does not seem to do anything. I have tried so many combinations of things and nothing is working. Have raised an question on [SO](https://stackoverflow.com/questions/49265016/how-to-recognise-file-name-for-syntax-highlighting-in-atom-grammar-file) and also on [Atom's user page](https://discuss.atom.io/t/how-to-recognise-file-name-for-syntax-highlighting/53288) to see if anyone can point me in the right direction.

**Comment by vsoch** [comment]
haha, your timing is funny, I'm doing the same thing and I haven't figured it out either :) I think the question and issue should bring some well needed help! My searching thus far is failing me, it keeps bringing back how to match filenames for a search (but not for the syntax.)

**Comment by vsoch** [comment]
I'm looking at other languages hoping to find an example --> https://github.com/atom?utf8=%E2%9C%93&q=language&type=&language=

**Comment by mbhall88** [comment]
An answer on [my atom question](https://discuss.atom.io/t/how-to-recognise-file-name-for-syntax-highlighting/53288/3) gives some hint at how to start trying to organise this. Not really sure how to implement it though. Seems like Atom is not super flexible in how it parses filetypes and the snippet would allow us to define the parsing in `javascript` (I assume that's the language in the snippet). Just not sure where this file would go and am struggling to get ideas from other packages about how they do this.  
Hopefully someone else will add a more detailed answer.

**Comment by vsoch** [comment]
I'll do some digging to see if I can poke around and understand how this works too - I'm new to Atom as well! I'm super tired today so likely I can get to this in the next few days. I definitely want to learn a little mode nodejs / express / atom in general so it's a good problem we have here :)

**Comment by vsoch** [comment]
oh I think I'm figuring this out! I am going for a quick run but I'll test out my intuition and send an update a little later today! This atom stuff is pretty neat, but based on the design I understand why it has reputation to be slow.

**Comment by vsoch** [comment]
okay I'm going to merge your PR, then open another PR with what I figured out!

**Comment by vsoch** [comment]
okay check out here! --> https://github.com/singularityhub/language-singularity/pull/3

**Comment by mbhall88** [comment]
I think this needs to be reopened. After the release of v2.0 my `Singularity.*` files are not being recognised as Singularity on either load or save.

**Comment by vsoch** [comment]
Yeah we just had a PR that removed the lib.js! Because it was calling every file a Singularity file :/ Can you try adding here:

```bash
'fileTypes': [
    'Singularity'
    'def'
]
```
something like this?

```bash
'fileTypes': [
    'Singularity'
    'Singularity.*'
    'def'
]
```

**Comment by vsoch** [comment]
hey @tsnowlan your PR removed the lib/main.js, could you take a look at this issue?

**Comment by tsnowlan** [comment]
Sure thing.

From the atom issue we opened (atom/atom#18485), the standard behavior of `fileTypes` is to match suffixes not prefixes, so not matching `Singularity.*` is the grammar working "properly" from Atom's POV. Which is why you guys had to add `lib/main.js` to catch them and why the functionality broke when I nuked the directory.

Sorry for missing the purpose of that one. I'll make a branch to re-add and see if I can fix the greedy matching instead of just removing it entirely.

**Comment by vsoch** [comment]
Cool thanks @tsnowlan, so greatly appreciated! I'll take the blame here for moving forward the nuke without remembering why we added it in the first place, haha. @mbhall88 hang tight!

**Comment by tsnowlan** [comment]
Okay, I've got an idea  how to do this, but I want to confirm the requirements for forcing the highlighting.

Is the ideal match:
* `^Singularity.*`
* `^Singularity\..*`
* `^Singularity\.\w*` - using perl-style `\w = [a-zA-Z0-9_-]`
* something else?

I'd also like to propose that it only change the grammar if the current grammar is Plain Text. That way it won't override the syntax for `Singularity.pl`, `Singularity.h`, etc.

**Comment by vsoch** [comment]
Yes! To go through your list (in words) I can confirm:

 - Any file that starts with Singularity and ends with some tag (Singularity.<tag>) is a recipe
 - Would this escape the period, meaning that the first would match "Singularityfile" ? We don't want that, I don't think (it could match a directory for example).

And completely agree. So maybe the (appended list, including the def extension) would be:

* `^Singularity\..*`   # assuming this matches Singularity.<tag>
* `^Singularity\.\w*` - using perl-style `\w = [a-zA-Z0-9_-]`

And then the def. Wouldn't the first above match all cases of the second? Do different users have different regex parsers?

**Comment by tsnowlan** [comment]
Nah it all uses the same parser, I just defined `\w` because there are strange people who don't have regex classes memorized.

The built-in functionality already covers matching `^Singularity$` and `.*\.def$`, so I'm ignoring those. This will just matching anything whose title starts with the case-sensitive string (no regex) `Singularity.` and is currently using the plain text grammar. This will happen on save, title change, and (bonus) on open as well.

PR incoming.
