### ISSUE TITLE
recognize all filetypes as a singularity file

### ISSUE THREAD

**Issue by chrstphdm** [singularityhub/language-singularity#4]
Hi there !

Great package, except it recognize all filetypes as a singularity file after making a save action (ctrl-s for exemple). Everything's correct with package disabled. 

I'll be happy to debug on my own but I don't know how.
Thank you !

**Comment by vsoch** [comment]
If you can contribute to the plugin to fix it up, it would be greatly appreciated!  I don't know the detail to fix off the top of my head.

**Comment by tsnowlan** [comment]
It only happens when there is a file already open with `Singularity` in its name.

Still no idea how to fix it, but that's a little bit more info on the issue at least.

**Comment by tsnowlan** [comment]
Workaround: use `filename.def` format instead of `*Singularity*`

**Comment by vsoch** [comment]
We should fix for Singularity though - did you try changing "Singularity" to `SIngularity.*` ?

**Comment by tsnowlan** [comment]
Yeah. Syntax will get set to Singularity on file save when there is a buffer name matching `.*Singularity.*`. That buffer doesn't even need to be an actually saved file, a temporary file (e.g., with `atom Singularity` but haven't yet hit save) open will still trigger the syntax change in other tabs. If multiple windows are open, only the one with the matching file is affected.

**Comment by tsnowlan** [comment]
Also, running `auto-detect` on affected files afterwards will correctly re-assign the syntax highlighting, but it still gets set to Singularity again after the next save. Similarly, newly opened files are correctly assigned. It seems limited to syntax change on save.

It's such a weird bug I almost think it's something with atom itself, but I've never seen it happen with any other language grammar.

**Comment by vsoch** [comment]
You wouldn't want it to be Singularity with a star in the beginning, it would only need to be `Singularity.*` (star to match anything at the end).

**Comment by tsnowlan** [comment]
Right. I was trying to say it currently affects any file matching that pattern, not that it's a desired behavior

**Comment by vsoch** [comment]
Okay, I think this is an issue that goes higher up than the plugin - it's not well established how to match patterns not just based on an extension (and this is something that we would want to do). I've opened an issue [here](https://github.com/atom/atom/issues/18485), please add comment as you see necessary! :point_right:  https://github.com/atom/atom/issues/18485

**Comment by vsoch** [comment]
Fixed and released as 2.0.0.

**Comment by vsoch** [comment]
https://atom.io/packages/language-singularity

**Comment by tsnowlan** [comment]
That one was driving me batty, but I didn't even notice that `lib/main.js` was there let alone thought to look at it. :man_facepalming: Though admittedly, I generally try to pretend javascript doesn't exist.

Thanks for the quick responses on this once we got rolling!
